export component KeyButton inherits Rectangle {
    in property <string> text;
    in property <bool> special: false;
    callback clicked;
    in property <string> icon-path: "";
    background: touch.pressed ? #333333 : (special ? #2a2a2a : #252525);
    border-radius: 8px;
    height: 50px;
    if (root.icon-path == ""): Text {
        text: root.text;
        color: special ? #81D4FA : white;
        font-size: 24px;
        font-weight: 500;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
    if (root.icon-path != ""): Path {
        width: 24px;
        height: 24px;
        commands: root.icon-path;
        fill: special ? #81D4FA : white;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }
    touch := TouchArea {
        clicked => {
            root.clicked();
        }
    }
}
