export component SectionHeader inherits HorizontalLayout {
    in property <string> title;
    spacing: 12px;
    padding-top: 25px;
    padding-bottom: 15px;
    Rectangle {
        width: 4px;
        height: 24px;
        background: #4FC3F7; // Colors.light_blue
        border-radius: 2px;
    }

    Text {
        text: title;
        font-size: 18px;
        font-weight: 800;
        color: #81D4FA;
        vertical-alignment: center;
        letter-spacing: 1.5px;
    }
}
