export component SelectionItem inherits Rectangle {
    in property <string> text;
    in property <bool> selected;
    callback clicked();
    height: 60px;
    border-radius: 16px;
    background: root.selected ? #FFAB4025 : #252525;
    border-width: 2px;
    border-color: root.selected ? #FFAB40 : #FFFFFF08;
    animate background { duration: 150ms; }
    animate border-color { duration: 150ms; }
    TouchArea {
        clicked => {
            root.clicked();
        }
    }

    Text {
        text: root.text;
        vertical-alignment: center;
        horizontal-alignment: center;
        color: root.selected ? #FFAB40 : #FFFFFFCC;
        font-weight: root.selected ? 800 : 500;
        font-size: 14px;
        letter-spacing: 1.5px;
        animate color { duration: 150ms; }
    }
}
