export component SidebarItem inherits Rectangle {
    in property <string> text;
    in property <string> subtext: "";
    in property <string> icon-path;
    in property <color> icon-color: #FFAB40;
    in property <bool> selected: false;
    callback clicked();
    height: 60px;
    border-radius: 16px;
    background: root.selected ? #FFAB4015 : #2C2C2C; // Slightly lighter than bg
    border-width: 1px;
    border-color: root.selected ? #FFAB40 : #FFFFFF10;
    TouchArea {
        clicked => {
            root.clicked();
        }
    }

    HorizontalLayout {
        padding-left: 16px;
        padding-right: 16px;
        spacing: 16px;
        alignment: start;
        
        // Icon
        Rectangle {
            width: 32px;
            height: 32px;
            border-radius: 8px;
            background: #FFFFFF10;
            y: (parent.height - self.height) / 2;
            Path {
                width: 24px;
                height: 24px;
                x: (parent.width - self.width) / 2;
                y: (parent.height - self.height) / 2;
                commands: root.icon-path;
                fill: root.icon-color;
            }
        }

        VerticalLayout {
            alignment: center;
            Text {
                text: root.text;
                font-size: 16px;
                font-weight: 800;
                color: #FFFFFF;
                letter-spacing: 1px;
            }

            if (root.subtext != ""): Text {
                text: root.subtext;
                font-size: 10px;
                color: #FFFFFF66;
            }
        }
    }
}
