export component InventoryItem inherits Rectangle {
    in property <string> label;
    in property <string> value;
    in property <bool> has-focus: false;
    callback request-focus();
    height: 85px;
    background: #1e1e1e;
    border-radius: 18px;
    HorizontalLayout {
        padding-left: 20px;
        padding-right: 20px;
        alignment: space-between;
        Text {
            text: label;
            color: #ffffff;
            vertical-alignment: center;
            font-size: 18px;
            font-weight: 500;
        }

        Rectangle {
            width: 100px;
            height: 45px;
            background: #121212;
            border-radius: 12px;
            y: (parent.height - self.height) / 2;
            border-width: has-focus ? 1.5px : 0px;
            border-color: #ff9d00;
            TouchArea {
                clicked => {
                    root.request-focus();
                }
            }

            // Wrapper for alignment
            HorizontalLayout {
                padding-right: 10px;
                alignment: end;
                spacing: 2px;
                
                // Value text
                Text {
                    text: value == "" ? "0" : value;
                    color: value == "" ? #3b3b3b : #ff9d00;
                    font-size: 20px;
                    font-weight: 800;
                    vertical-alignment: center;
                    horizontal-alignment: right;
                }
                
                // Fake cursor (solid for now to avoid animation issues)
                if (has-focus): Rectangle {
                    width: 2px;
                    height: 24px;
                    background: #ff9d00;
                    y: (parent.height - self.height) / 2;
                }
            }
        }
    }
}
