import { Button, VerticalBox, ScrollView } from "std-widgets.slint";
import { InventoryItem } from "../components/inventory_item.slint";
import { SectionHeader } from "../components/section_header.slint";
import { TopBar } from "../components/top_bar.slint";


export component DoorScreen inherits Rectangle {
    in-out property <[string]> inv_vals;
    in-out property <[int]> inv_lengths;
    in-out property <int> active_idx;
    in property <string> project-name: "ELECTRIC";
    in-out property <length> viewport-y; // Exposed for scroll tracking
    callback selective-share-pressed();
    callback trash-pressed();
    callback request-activate-item(int);
    callback request-append-digit(string);
    callback request-backspace();
    VerticalLayout {
        TopBar {
            title: root.project-name;
            selective-share-pressed => {
                root.selective-share-pressed();
            }
            trash-pressed => {
                root.trash-pressed();
            }
        }

        Flickable {
            viewport-y <=> root.viewport-y;
            viewport-height: content.preferred-height;
            content := VerticalBox {
                padding-left: 16px;
                padding-right: 16px;
                padding-bottom: 350px;
                spacing: 12px;
                alignment: start;
                SectionHeader {
                    title: "PUERTA";
                }

                InventoryItem {
                    label: "60m";
                    value: root.inv_vals[19];
                    has-focus: root.active_idx == 19;
                    request-focus => {
                        root.request-activate-item(19);
                    }
                }

                InventoryItem {
                    label: "70m";
                    value: root.inv_vals[20];
                    has-focus: root.active_idx == 20;
                    request-focus => {
                        root.request-activate-item(20);
                    }
                }

                InventoryItem {
                    label: "80m";
                    value: root.inv_vals[21];
                    has-focus: root.active_idx == 21;
                    request-focus => {
                        root.request-activate-item(21);
                    }
                }

                InventoryItem {
                    label: "90m";
                    value: root.inv_vals[22];
                    has-focus: root.active_idx == 22;
                    request-focus => {
                        root.request-activate-item(22);
                    }
                }
            }
        }
    }
}
